<#
.SYNOPSIS
    One-time developer environment setup for EasyTimer on Windows 11.

.DESCRIPTION
    Detects the installed Visual Studio / Build Tools installation via vswhere,
    finds the current MSVC toolchain and Windows SDK versions dynamically,
    and writes the necessary [target.x86_64-pc-windows-msvc] section into
    the user-level Cargo config (~/.cargo/config.toml).

    This must be run once per developer machine. It does NOT commit anything
    to the repository — all generated paths stay in the user's local config.

.NOTES
    Run with: powershell -ExecutionPolicy Bypass -File scripts\setup-windows.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── 1. Locate vswhere ────────────────────────────────────────────────────────
$vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vsWhere)) {
    Write-Error "vswhere.exe not found at '$vsWhere'. Install Visual Studio Build Tools first:`n  winget install --id Microsoft.VisualStudio.2022.BuildTools --override `"--quiet --wait --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended`""
    exit 1
}

# ── 2. Find VS installation path ─────────────────────────────────────────────
$vsInstallPath = & $vsWhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $vsInstallPath) {
    Write-Error "No Visual Studio installation with VC++ tools found. Run:`n  winget install --id Microsoft.VisualStudio.2022.BuildTools --override `"--quiet --wait --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended`""
    exit 1
}
Write-Host "Found VS installation: $vsInstallPath"

# ── 3. Find latest MSVC toolchain version ────────────────────────────────────
$msvcBase = Join-Path $vsInstallPath "VC\Tools\MSVC"
if (-not (Test-Path $msvcBase)) {
    Write-Error "MSVC tools directory not found at '$msvcBase'."
    exit 1
}
$msvcVersion = Get-ChildItem -Path $msvcBase -Directory | Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty Name
if (-not $msvcVersion) {
    Write-Error "No MSVC version found in '$msvcBase'."
    exit 1
}
$msvcPath = Join-Path $msvcBase $msvcVersion
Write-Host "Found MSVC version: $msvcVersion  ->  $msvcPath"

# ── 4. Verify linker exists ───────────────────────────────────────────────────
$linkerPath = Join-Path $msvcPath "bin\Hostx64\x64\link.exe"
if (-not (Test-Path $linkerPath)) {
    Write-Error "MSVC linker not found at '$linkerPath'."
    exit 1
}

# ── 5. Find latest Windows SDK version ───────────────────────────────────────
$sdkLibBase = "${env:ProgramFiles(x86)}\Windows Kits\10\Lib"
if (-not (Test-Path $sdkLibBase)) {
    Write-Error "Windows SDK Lib directory not found at '$sdkLibBase'. The VCTools workload should install it with --includeRecommended."
    exit 1
}
$sdkVersion = Get-ChildItem -Path $sdkLibBase -Directory | Where-Object { $_.Name -match '^\d+\.\d+\.\d+\.\d+$' } | Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty Name
if (-not $sdkVersion) {
    Write-Error "No versioned Windows SDK directory found in '$sdkLibBase'."
    exit 1
}
Write-Host "Found Windows SDK version: $sdkVersion"

# ── 6. Build path values ──────────────────────────────────────────────────────
$msvcLibPath  = Join-Path $msvcPath "lib\x64"
$sdkUmPath    = "${env:ProgramFiles(x86)}\Windows Kits\10\Lib\$sdkVersion\um\x64"
$sdkUcrtPath  = "${env:ProgramFiles(x86)}\Windows Kits\10\Lib\$sdkVersion\ucrt\x64"

foreach ($p in @($msvcLibPath, $sdkUmPath, $sdkUcrtPath)) {
    if (-not (Test-Path $p)) {
        Write-Error "Expected library path not found: '$p'"
        exit 1
    }
}

# Escape backslashes for TOML
$linkerToml   = $linkerPath  -replace '\\', '\\'
$msvcLibToml  = $msvcLibPath -replace '\\', '\\'
$sdkUmToml    = $sdkUmPath   -replace '\\', '\\'
$sdkUcrtToml  = $sdkUcrtPath -replace '\\', '\\'

# ── 7. Write user-level Cargo config ─────────────────────────────────────────
$cargoConfigDir  = Join-Path $env:USERPROFILE ".cargo"
$cargoConfigPath = Join-Path $cargoConfigDir "config.toml"

$section = @"

# ── EasyTimer: Windows MSVC toolchain (generated by scripts/setup-windows.ps1) ─
# Re-run the script if you update Visual Studio or the Windows SDK.
[target.x86_64-pc-windows-msvc]
linker = "$linkerToml"
rustflags = [
  "-L", "$msvcLibToml",
  "-L", "$sdkUmToml",
  "-L", "$sdkUcrtToml",
]
"@

if (-not (Test-Path $cargoConfigDir)) {
    New-Item -ItemType Directory -Path $cargoConfigDir | Out-Null
}

$marker = "[target.x86_64-pc-windows-msvc]"

if (Test-Path $cargoConfigPath) {
    $existing = Get-Content $cargoConfigPath -Raw
    if ($existing -match [regex]::Escape($marker)) {
        Write-Host ""
        Write-Host "WARNING: $cargoConfigPath already contains a [target.x86_64-pc-windows-msvc] section."
        Write-Host "         Review it manually and update the linker/rustflags paths if they are outdated."
        Write-Host "         Detected paths this run:"
        Write-Host "           linker   = $linkerPath"
        Write-Host "           MSVC lib = $msvcLibPath"
        Write-Host "           SDK um   = $sdkUmPath"
        Write-Host "           SDK ucrt = $sdkUcrtPath"
        exit 0
    }
    # Append to existing config
    Add-Content -Path $cargoConfigPath -Value $section
} else {
    Set-Content -Path $cargoConfigPath -Value $section.TrimStart()
}

Write-Host ""
Write-Host "SUCCESS: Wrote to $cargoConfigPath"
Write-Host "  linker   = $linkerPath"
Write-Host "  MSVC lib = $msvcLibPath"
Write-Host "  SDK um   = $sdkUmPath"
Write-Host "  SDK ucrt = $sdkUcrtPath"
Write-Host ""
Write-Host "You can now run: yarn tauri dev"
